name: app
description: A sample command-line application.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.4.1
  github: ^9.14.0
  github_actions_toolkit: ^0.0.8
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.1
